### ISSUE TITLE
Logging is dumping contents to the browser

### ISSUE THREAD

**Issue by tomworks** [uvasoftware/scanii-php#9]
Hi

Currently the logging method is using var_dump to add content to strings e.g. 

``$this->log('post contents ' . var_dump($post_contents));``

This actually just dumps content to the browser, we get away with it on server side calls but when this is used in an ajax request that makes a ->process call the var_dump output is added to the response and make content invalid.

Could probably easily swapped for :

``$this->log('post contents ' . var_export($post_contents, true));``

Or use output buffering ob_start ?

Thanks

Tom

**Comment by rferreira** [comment]
thanks Tom, let me dig into this to ensure I understand the differences between var_dump and var_export but, at first glance, what you are suggesting sounds reasonable.

**Comment by rferreira** [comment]
@tomworks, new release 3.2.0 is out, thanks for the issue.

**Comment by tomworks** [comment]
I think the issue still persists as:

``var_export($post_contents);``

should actually be:

``var_export($post_contents, true);``

**Comment by rferreira** [comment]
well that's a bummer, reopening this ticket.

**Comment by rferreira** [comment]
All right, do you mind testing our release v3.2.1 I just pushed out?

**Comment by tomworks** [comment]
I can’t see 3.2.1, currently composer only showing:

dev-master, v3.x-dev, * v3.1.0, v3.0.0, v2.2.2, v2.1, dev-dependabot/composer/phpunit/phpunit-tw-6.0or-tw-9.0, dev-raf/feature

**Comment by rferreira** [comment]
Can you try now? It's showing up https://packagist.org/packages/uvasoftware/scanii-php#v3.2.1 - I think there's just a delay between a package being published and composer picking it up.

**Comment by tomworks** [comment]
Thanks Rafael, tested and seems to work well now.
